### ISSUE TITLE
SOLID: A cancel on authentication to be graciously handled

### ISSUE THREAD

**Issue by gjwgit** [anusii/solid#38]
## Description

When on the Authenticate screen in the browser:

![Image](https://github.com/anusii/solid/assets/1681429/3e2c996c-a71c-417c-8ef2-853ce6a2c56c)

I click cancel and the app is blocked with an exception:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      TokenResponse.idToken (package:solid_auth/src/openid/src/model/token_response.dart:25:66)
#1      Credential.generateLogoutUrl (package:solid_auth/src/openid/src/openid.dart:231:31)
#2      authenticate (package:solid_auth/solid_auth_client.dart:220:35)
<asynchronous suspension>
#3      solidAuthenticate (package:solid/src/solid/authenticate.dart:78:22)
<asynchronous suspension>
#4      _SolidLoginState.build.<anonymous closure> (package:solid/src/solid/login.dart:212:28)
<asynchronous suspension>
```

It seems the code to capture this is not doing so.

**Comment by gjwgit** [comment]
I had to replace `on ()` with `catch ()` for it to catch the above error.

I now get the popup but on clicking Ok it remains with the busy animation:

![image](https://github.com/anusii/solid/assets/1681429/46adda20-d450-487c-b8f3-e531f3250a81)

**Comment by gjwgit** [comment]
I have a solution of sorts - Replacing the failed auth popup with a navigate to the login app (the current widget). 

Please review.
